---
title: "FinalProject"
author: "Hyewon Choi"
date: "12/8/2017"
output:
  pdf_document: default
  html_document: default
---

#Loading the data, observing duplicates
```{r load libraries & data}
library(readr)
library(readxl)
library(janitor)
library(tidyverse)
library(pander)
library(leaps)
library(HH)
library(boot)
library(qboxplot)


hos = read_excel("./data/GHProject_Dataset.xlsx")

duplicates = data.frame(table(hos$PatientID)) 

duplicates = duplicates[duplicates$Freq > 1,] %>%
  rename(PatientID = Var1)
#69 patients visited the hospital more than once, 68 visited twice and 1 visited three times

hos_duplicates = merge(duplicates, hos)
```

#Tidying the data
```{r tidy data}
hos_tidy <- hos %>% 
  clean_names() %>%
  dplyr::select(-loshours, -postalcode, -facilityname, -facilityzip) %>%
  dplyr::group_by(patientid) %>% 
  dplyr::filter(!duplicated(patientid)) %>%
  ungroup(patientid)
```

#Summary Statistics
```{r summary statistics}
summary_losdays2 = hos_tidy %>% 
  dplyr::select(losdays2) %>%
  summarize(variable = names(.), 
            n = n(), mean = mean(losdays2), 
            sd = sd(losdays2), 
            minimum = min(losdays2), 
            maximum = max(losdays2), 
            median = median(losdays2))

summary_ageyear = hos_tidy %>% 
  dplyr::select(ageyear) %>%
  summarize(variable = names(.), n = n(), 
            mean = mean(ageyear),
            sd = sd(ageyear),
            minimum = min(ageyear),
            maximum = max(ageyear),
            median = median(ageyear))

summary_evisit = hos_tidy %>% 
  dplyr::select(evisit) %>%
  summarize(variable = names(.),
            n = n(),
            mean = mean(evisit),
            sd = sd(evisit),
            minimum = min(evisit),
            maximum = max(evisit),
            median = median(evisit))

summary = rbind(summary_losdays2, summary_ageyear, summary_evisit)
pander(summary)
```

#Data observations & building dummies
```{r observing data}
hos_tidy %>%
  ggplot(aes(x = losdays2)) + 
    geom_histogram() +
    labs(title = "Figure 1: Length of Stay",
         x = "Length of Stay (Days)",
         y = "Count")
  

```

```{r omit na}
fill_na = function(x) {
  if (is.numeric(x)){
   mean = mean(x, na.rm = TRUE)
   x = replace(x, is.na(x), mean)
  } else {x = x} 
    
  return(x)
}

hos_tidy_omitna = map_df(hos_tidy, fill_na)


```

```{r}
outliersZ <- function(data, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2) {
    #compute standard deviation (sample version n = n [not n-1])
    stdev <- sqrt(sum((data - mean(data, na.rm = T))^2, na.rm = T) / sum(!is.na(data)))
    #compute absolute z values for each value
    absZ <- abs(data - mean(data, na.rm = T)) / stdev
    #subset data that has absZ greater than the zCutOff and replace them with replace
    #can also replace with other values (such as max/mean of data)
    data[absZ > zCutOff] <- replace 
    
    if (values == TRUE) {
        return(round(absZ, digits)) #if values == TRUE, return z score for each value
    } else {
        return(round(data, digits)) #otherwise, return values with outliers replaced
    }
}

hos_tidy_omitna$bmi = outliersZ(hos_tidy_omitna$bmi, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$temperature = outliersZ(hos_tidy_omitna$temperature, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$heartrate = outliersZ(hos_tidy_omitna$heartrate, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$respirationrate = outliersZ(hos_tidy_omitna$respirationrate, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$bpdiastolic = outliersZ(hos_tidy_omitna$bpdiastolic, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$bpsystolic = outliersZ(hos_tidy_omitna$bpsystolic, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

## 99.9% cut off
```


```{r omit na again}
fill_na = function(x) {
  if (is.numeric(x)){
   mean = mean(x, na.rm = TRUE)
   x = replace(x, is.na(x), mean)
  } else {x = x} 
    
  return(x)
}

hos_tidy_omitna = map_df(hos_tidy_omitna, fill_na)

hos_tidy_omitna = hos_tidy_omitna %>%
  filter(!o2sat > 100)
```

  
### Stepwise selection
```{r Stepwise selection}
hos_tidy_omitna = hos_tidy_omitna %>%
  mutate(log_losdays2 = log(losdays2)) %>%
  na.omit()
mult.fit <- lm(log_losdays2 ~ is30dayreadmit + ageyear + evisit+ cindex + maritalstatus + insurancetype + race + respirationrate + o2sat + heartrate + bmi + temperature + bpsystolic + bpdiastolic + mews + icu_flag, data = hos_tidy_omitna) 
summary(mult.fit)

z = step(mult.fit, direction = 'both') 
summary(z)

#mews score based on bp, respiration, heartrate & temp and is a less significant variable than bp, resp $ temp 
#the two bp readings are correlated
#of all the dummy variables, only insurancetype was significant

```

### Criterion-based procedures
```{r criterion}
mult.fit <- lm(log_losdays2 ~ is30dayreadmit + evisit+ cindex + ageyear + maritalstatus + insurancetype + race + respirationrate + o2sat + heartrate + bmi + temperature + bpsystolic + bpdiastolic + mews + icu_flag, data = hos_tidy_omitna) 

best <- function(model, ...) 
{
  subsets <- regsubsets(formula(model), model.frame(model), ...)
  subsets <- with(summary(subsets),
                  cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))
  
  return(subsets)
}  

best(mult.fit, nbest = 1)
```

#Final model
```{r}
mult.fit2 <- lm(log_losdays2 ~ is30dayreadmit + evisit+ cindex + ageyear +  respirationrate + heartrate + temperature + bpsystolic, data = hos_tidy_omitna) 

best(mult.fit2, nbest = 1)

vif(mult.fit2)
```

#Checking outliers
```{r}
# # Simple linear regression
# reg_hos<-lm(hos_tidy_omitna$log_losdays2~hos_tidy_omitna$is30dayreadmit)


stu_res<-rstandard(mult.fit2)
outliers_y<-stu_res[abs(stu_res)>2.5]

#removing outliers
hos_tidy_omitna_outl <- hos_tidy_omitna[c(-6,-232,-277,-368,-411,-514,-535,-557,-562,-604,-629,-704,-772,-824,-838,-852,-879,-982,-996,-1114,-1337,-1395,-1438,-1446, -1471,-1491,-1517,-1552,-1605,-1639,-1682,-1697,-1882,-2002,-2024,-2071,-2153,-2395,-2460,-2525,-2554,-2769,-2786,-2828,-2852, -2926, -3086, -3103, -3104, -3105, -3116, -3131, -3170,-3174,-3232,-3298,-3299,-3318,-3329,-3332, -3405),]

influence.measures(mult.fit2)

```

#Vif
```{r}
library(HH)
vif(mult.fit2)
```

#Building the model without the outliers
```{r}
mult.fit3 <- lm(log_losdays2 ~ is30dayreadmit + evisit+ cindex + ageyear +  respirationrate + heartrate + temperature + bpsystolic, data = hos_tidy_omitna_outl) 

best(mult.fit3, nbest = 1)
summary(mult.fit3)
```

#Bootstrap
```{r}
set.seed(1)


boot.fn<-function(data, index){
	return(coef(lm(log_losdays2 ~ is30dayreadmit + evisit+ cindex + ageyear +  respirationrate + heartrate  + temperature + bpsystolic , data = hos_tidy_omitna, subset=index)))
}
boot.fn(hos_tidy_omitna,1:3431)


set.seed(1)


boot.fn(hos_tidy_omitna,sample(3431,3431,replace=T))



boot(hos_tidy_omitna_outl, boot.fn, 1000)

# How does it compare to the original (non-bootstrap) estimates?
summary(mult.fit3)
```




#Residuals
```{r}
par(mfrow=c(2,2))
plot(mult.fit2)
```
