---
title: "FinalProject"
author: "Hyewon Choi"
date: "12/8/2017"
output:
  html_document: default
  pdf_document: default
---

#Loading the data, observing duplicates
```{r load libraries & data}
library(readr)
library(readxl)
library(janitor)
library(pander)
library(leaps)
library(boot)
library(tidyverse)




hos = read_excel("./data/GHProject_Dataset.xlsx")

#You can view the frequency for each observation using the table()
View(table(hos$PatientID)) 






#In this chunk, the goal is to look at the duplicates, which are the patients
#that appear more than once. we don't want them but we take a look at it.



#putting it into a data frame
dataframe_id = data.frame(table(hos$PatientID)) 

#Now it is in a data frame form, meaning that I can view a table of it.
#The below code picks out the 8th column and the 8th column's entire row.
dataframe_id[8, ]
#Below codes shows all of the 8th column's and  first row's observation
dataframe_id[8,1]
##
The form is [column, row]
dataframe_id[8,2] #this is 8th column and its 2nd row.
dataframe_id[15,1] #this is 15th column and its 1st row.

#What the below code does is that first it pulls out the observations that appear more than once 
dataframe_id = dataframe_id[dataframe_id$Freq > 1,] %>%
  rename(PatientID = Var1)  #the new name is PatientID
View(dataframe_id)
#69 patients visited the hospital more than once, 68 visited twice and 1 visited three times

#below is merging the ones that took out the duplicate id's with the original data set.
hos_duplicates = merge(dataframe_id, hos)
```


#Tidying the data
```{r tidy data}
hos_tidy <- hos %>% 
  clean_names() %>%
  dplyr::select(-loshours, -postalcode, -facilityname, -facilityzip) %>%
  dplyr::group_by(patientid) %>% 
  dplyr::filter(!duplicated(patientid)) %>%  #It drops out the duplicates of id's
  ungroup(patientid)
```

#Data observations & building dummies
```{r observing data}
hos_tidy %>%
  ggplot(aes(x = losdays2)) + 
    geom_histogram() +
    labs(title = "Figure 1: Length of Stay",
         x = "Length of Stay (Days)",
         y = "Count")
  
```

```{r omit na}
#Below is filling out the NA's with each column's mean 
fill_na = function(x) {
  if (is.numeric(x)){
   mean = mean(x, na.rm = TRUE)
   x = replace(x, is.na(x), mean)
  } else {x = x} 
    
  return(x)
}

hos_tidy_omitna = map_df(hos_tidy, fill_na)

```

```{r}
outliersZ <- function(data, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2) {
  
    #compute standard deviation (sample version n = n [not n-1])
    stdev <- sqrt(sum((data - mean(data, na.rm = T))^2, na.rm = T) / sum(!is.na(data)))
    #compute absolute z values for each value
    absZ <- abs(data - mean(data, na.rm = T)) / stdev
    #subset data that has absZ greater than the zCutOff and replace them with replace
    #can also replace with other values (such as max/mean of data)
    data[absZ > zCutOff] <- replace 
    
    if (values == TRUE) {
        return(round(absZ, digits)) #if values == TRUE, return z score for each value
    } else {
        return(round(data, digits)) #otherwise, return values with outliers replaced
    }

}


#So, here below codes are filtering out the outliers with the z score of 3.291, which is a 99.9% cut off .

hos_tidy_omitna$bmi = outliersZ(hos_tidy_omitna$bmi, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$temperature = outliersZ(hos_tidy_omitna$temperature, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$heartrate = outliersZ(hos_tidy_omitna$heartrate, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$respirationrate = outliersZ(hos_tidy_omitna$respirationrate, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$bpdiastolic = outliersZ(hos_tidy_omitna$bpdiastolic, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

hos_tidy_omitna$bpsystolic = outliersZ(hos_tidy_omitna$bpsystolic, zCutOff = 3.291, replace = NA, values = FALSE, digits = 2)

## 99.9% cut off
```


```{r omit na again}
fill_na = function(x) {
  if (is.numeric(x)){
   mean = mean(x, na.rm = TRUE)
   x = replace(x, is.na(x), mean)
  } else {x = x} 
    
  return(x)
}

hos_tidy_omitna = map_df(hos_tidy_omitna, fill_na)

hos_tidy_omitna = hos_tidy_omitna %>%
  filter(!o2sat > 100)
```

#Summary Statistics
```{r summary statistics}
summary_losdays2 = hos_tidy_omitna %>% 
  dplyr::select(losdays2) %>%
summarize(variable = names(.), 
            n = n(), mean = mean(losdays2), 
            sd = sd(losdays2), 
            minimum = min(losdays2), 
            maximum = max(losdays2), 
            median = median(losdays2))


summary_ageyear = hos_tidy_omitna %>% 
  dplyr::select(ageyear) %>%
  summarize(variable = names(.), n = n(), 
            mean = mean(ageyear),
            sd = sd(ageyear),
            minimum = min(ageyear),
            maximum = max(ageyear),
            median = median(ageyear))


summary_evisit = hos_tidy_omitna %>% 
 dplyr:: select(evisit) %>%
  summarize(variable = names(.),
            n = n(),
            mean = mean(evisit),
            sd = sd(evisit),
            minimum = min(evisit),
            maximum = max(evisit),
            median = median(evisit))

summary_bmi = hos_tidy_omitna %>% 
  dplyr::select(bmi) %>%
  summarize(variable = names(.),
            n = n()-sum(is.na(hos_tidy$bmi)),
            mean = mean(na.omit(bmi)),
            sd = sd(na.omit(bmi)),
            minimum = min(na.omit(bmi)),
            maximum = max(na.omit(bmi)),
            median = median(na.omit(bmi)))


summary_bpsystolic = hos_tidy_omitna %>% 
  dplyr::select(bpsystolic) %>%
  summarize(variable = names(.),
            n = n()-sum(is.na(hos_tidy$bpsystolic)),
            mean = mean(na.omit(bpsystolic)),
            sd = sd(na.omit(bpsystolic)),
            minimum = min(na.omit(bpsystolic)),
            maximum = max(na.omit(bpsystolic)),
            median = median(na.omit(bpsystolic)))


summary_o2sat = hos_tidy_omitna %>% 
  dplyr::select(o2sat) %>%
  summarize(variable = names(.),
            n = n()-sum(is.na(hos_tidy$o2sat)),
            mean = mean(na.omit(o2sat)),
            sd = sd(na.omit(o2sat)),
            minimum = min(na.omit(o2sat)),
            maximum = max(na.omit(o2sat)),
            median = median(na.omit(o2sat)))


summary_temperature = hos_tidy_omitna %>% 
  dplyr::select(temperature) %>%
  summarize(variable = names(.),
            n = n()-sum(is.na(hos_tidy$temperature)),
            mean = mean(na.omit(temperature)),
            sd = sd(na.omit(temperature)),
            minimum = min(na.omit(temperature)),
            maximum = max(na.omit(temperature)),
            median = median(na.omit(temperature)))


summary_heartrate = hos_tidy_omitna %>% 
  dplyr::select(heartrate) %>%
  summarize(variable = names(.),
            n = n()-sum(is.na(hos_tidy$heartrate)),
            mean = mean(na.omit(heartrate)),
            sd = sd(na.omit(heartrate)),
            minimum = min(na.omit(heartrate)),
            maximum = max(na.omit(heartrate)),
            median = median(na.omit(heartrate)))


summary_respirationrate = hos_tidy_omitna %>% 
  dplyr::select(respirationrate) %>%
summarize(variable = names(.),
            n = n()-sum(is.na(hos_tidy$respirationrate)),
            mean = mean(na.omit(respirationrate)),
            sd = sd(na.omit(respirationrate)),
            minimum = min(na.omit(respirationrate)),
            maximum = max(na.omit(respirationrate)),
            median = median(na.omit(respirationrate)))


summary_bpdiastolic = hos_tidy_omitna %>% 
  dplyr::select(bpdiastolic) %>%
  summarize(variable = names(.),
            n = n()-sum(is.na(hos_tidy$bpdiastolic)),
            mean = mean(na.omit(bpdiastolic)),
            sd = sd(na.omit(bpdiastolic)),
            minimum = min(na.omit(bpdiastolic)),
            maximum = max(na.omit(bpdiastolic)),
            median = median(na.omit(bpdiastolic)))

summary = rbind(summary_losdays2, summary_ageyear, summary_evisit, summary_bmi, summary_bpsystolic, summary_o2sat, summary_temperature, summary_heartrate, summary_respirationrate, summary_bpdiastolic)
table_summary <-pander(summary)
```
  
### Stepwise selection
```{r Stepwise selection, cache=true }
hos_tidy_omitna = hos_tidy_omitna %>%
  mutate(log_losdays2 = log(losdays2)) %>%
  na.omit()
mult.fit <- lm(log_losdays2 ~ is30dayreadmit + ageyear + evisit+ cindex + maritalstatus + insurancetype + race + respirationrate + o2sat + heartrate + bmi + temperature + bpsystolic + bpdiastolic + mews + icu_flag, data = hos_tidy_omitna) 
summary_multfit <-summary(mult.fit)
#stepwise selection below
 z <- step(mult.fit, direction = 'both') 
sum_z <- summary(z) #the final model survived from the stepwise selection

#mews score based on bp, respiration, heartrate & temp and is a less significant variable than bp, resp $ temp 
#the two bp readings are correlated
#of all the dummy variables, only insurancetype was significant

```

### Criterion-based procedures
```{r criterion}
mult.fit <- lm(log_losdays2 ~ is30dayreadmit + evisit+ cindex + ageyear + maritalstatus + insurancetype + race + respirationrate + o2sat + heartrate + bmi + temperature + bpsystolic + bpdiastolic + mews + icu_flag, data = hos_tidy_omitna) 

best <- function(model, ...) 
{
  subsets <- regsubsets(formula(model), model.frame(model), ...)
  subsets <- with(summary(subsets),
                  cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))
  
  return(subsets)
}  

best_fit <- best(mult.fit, nbest = 1)
```

#Final model
```{r}
library(car)
mult.fit2 <- lm(log_losdays2 ~ is30dayreadmit + evisit+ cindex + ageyear +  respirationrate + heartrate + temperature + bpsystolic, data = hos_tidy_omitna) 

best_Fit2 <- best(mult.fit2, nbest = 1)
#Identify Collinearity by using vif. 
#VIF > 5 suggest that the coefficients might be misleading due to collinearity
vif_multfit2 <- vif(mult.fit2)
```

#Checking outliers
```{r}
# # Simple linear regression
# reg_hos<-lm(hos_tidy_omitna$log_losdays2~hos_tidy_omitna$is30dayreadmit)


stu_res<-rstandard(mult.fit2)
outliers_y<-stu_res[abs(stu_res)>2.5]

#removing outliers
hos_tidy_omitna_outl <- hos_tidy_omitna[c(-6,-232,-277,-368,-411,-514,-535,-557,-562,-604,-629,-704,-772,-824,-838,-852,-879,-982,-996,-1114,-1337,-1395,-1438,-1446, -1471,-1491,-1517,-1552,-1605,-1639,-1682,-1697,-1882,-2002,-2024,-2071,-2153,-2395,-2460,-2525,-2554,-2769,-2786,-2828,-2852, -2926, -3086, -3103, -3104, -3105, -3116, -3131, -3170,-3174,-3232,-3298,-3299,-3318,-3329,-3332, -3405),]

checking_influence <- influence.measures(mult.fit2)

```

#Vif
```{r}
library(HH)
vif_multfit2 <- vif(mult.fit2)
```

#Building the model without the outliers
```{r}
mult.fit3 <- lm(log_losdays2 ~ is30dayreadmit + evisit+ cindex + ageyear +  respirationrate + heartrate + temperature + bpsystolic, data = hos_tidy_omitna_outl) 

best_fit3 <- best(mult.fit3, nbest = 1)
summary_multfit3 <-summary(mult.fit3)
```

#Bootstrap
```{r}
set.seed(1)


boot.fn<-function(data, index){
	return(coef(lm(log_losdays2 ~ is30dayreadmit + evisit+ cindex + ageyear +  respirationrate + heartrate  + temperature + bpsystolic , data = hos_tidy_omitna_outl, subset=index)))
}
boot_result <- boot.fn(hos_tidy_omitna_outl,1:3431)


set.seed(1)


boot_result2 <- boot.fn(hos_tidy_omitna_outl,sample(3431,3431,replace=T))



boot_result3 <- boot(hos_tidy_omitna_outl, boot.fn, 1000)

# How does it compare to the original (non-bootstrap) estimates?
summary_Boot_3<- summary(mult.fit3)
```




#Residuals
```{r}
par(mfrow=c(2,2))
plot_residuals <- plot(mult.fit2)
```
